language: rust

addons:
  apt:
    update: true
    packages:
      - libasound2-dev
      - libudev-dev

rust:
  - nightly
  - stable

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux
  - osx
  - windows

before_script:
  - rustup component list

script:
  - cargo build --all
  - cargo build --examples --all
  - cargo test --all

jobs:
  include:
  - name: check_assets
    rust: stable
    script:
      - git clone --depth=1 https://github.com/ozkriff/zemeroth_assets assets
      - RUST_LOG=zemeroth=info cargo run -- --check-assets
  - name: fmt
    rust: stable
    install:
      - rustup component add rustfmt
      - rustfmt -V
    script:
      - cargo fmt --all -- --check
  - name: clippy
    rust: stable
    install:
      - rustup component add clippy
      - cargo clippy -V
    script:
      - cargo clippy --verbose -- -D warnings
  - name: wasm
    rust: stable
    install:
      - cargo install cargo-web
      - cargo web -V
    script:
      - ./utils/wasm/build.sh
