language: rust

# TODO: find a way to install SDL2 without sudo and disable it:
sudo: true

addons:
  apt:
    update: true
    packages:
    - libasound2-dev

cache: cargo

rust:
  - nightly
  - stable

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux
  - osx
  - windows

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
        && tar -xzvf SDL2-2.0.5.tar.gz
        && pushd SDL2-2.0.5
        && ./configure --prefix=/usr
        && make
        && sudo make install
        && popd;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update && brew install sdl2;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
        curl -O https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip
        && ls
        && 7z x SDL2-devel-2.0.5-VC.zip
        && ls
        && cp SDL2-2.0.5/lib/x64/* .
        && ls;
    fi

before_script:
- rustup component list

script:
  - cargo build --all
  - cargo build --examples --all
  - cargo test --all

jobs:
  include:
  - name: check_assets
    rust: stable
    script:
      - git clone --depth=1 https://github.com/ozkriff/zemeroth_assets assets
      - RUST_LOG=zemeroth=info cargo run -- --check-assets
  - name: fmt
    rust: nightly-2018-10-01
    install:
      - rustup component add rustfmt-preview
      - rustfmt -V
    script:
      - cargo fmt --all -- --check
  - name: clippy
    rust: nightly-2018-10-01
    install:
      - rustup component add clippy-preview
      - cargo clippy -V
    script:
      - cargo clippy --verbose -- -D warnings
