[package]
name = "zscene"
version = "0.1.0"
authors = ["Andrey Lesnikov <ozkriff@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Scene and Actions for gwg"
keywords = ["gamedev", "2D"]

[dependencies]
mq = { package = "macroquad", version = "0.3" }
